  version: '3'

  services:

    ghost:
      image: ghost:1-alpine
      restart: always
      ports:
        - 2368:2368
      depends_on:
        - "db"
      environment:
        # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
        database__client: mysql
        database__connection__host: db
        database__connection__user: root
        database__connection__password: example
        database__connection__database: ghost
      networks:
        - my_network

    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${example}
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - my_network

    volumes:
      db_data:

    networks:
      my_network: